apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: go-oscxgmzu 
  janus-idp.io/tekton: go-oscxgmzu
  backstage.io/kubernetes-id: go-oscxgmzu
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: go-oscxgmzu
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml